# Generated by Django 5.2.5 on 2026-03-23 08:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='photo',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='memories/'),
        ),
    ]
